In [7]:
import pandas as pd
import requests
from zipfile import ZipFile
from io import BytesIO

In [8]:
exe_url = 'https://raw.githubusercontent.com/OTRF/Security-Datasets/master/datasets/atomic/windows/execution/host/psh_python_webserver.zip'
cred_url = 'https://raw.githubusercontent.com/OTRF/Security-Datasets/master/datasets/atomic/windows/credential_access/host/empire_mimikatz_logonpasswords.zip'

In [9]:
# Display all columns and rows
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

## Execution Logs

In [10]:
# Reading the logs from the execution URL
zipFileRequest = requests.get(exe_url)
zipFile = ZipFile(BytesIO(zipFileRequest.content))
datasetJSONPath = zipFile.extract(zipFile.namelist()[0])

# Storing logs into a dataframe
exe_df = pd.read_json(path_or_buf=datasetJSONPath, lines=True)

### Execution Log Exploratory Data Analysis

In [11]:
# Sorting the logs by timestamp in ascending order
exe_data = exe_df.sort_values(by='@timestamp', ascending=True)

# Get all columns in the dataset
exe_columns = exe_data.columns.tolist()
print(exe_columns)

['Message', 'EventID', 'SourceName', 'TimeCreated', 'Hostname', 'Task', 'Level', 'Keywords', 'Channel', 'ProviderGuid', '@timestamp', 'SourcePort', 'LayerName', 'SourceAddress', 'Protocol', 'ProcessId', 'LayerRTID', 'FilterRTID', 'Application', 'RemoteMachineID', 'Direction', 'DestPort', 'RemoteUserID', 'DestAddress', 'ProcessID', 'CommandLine', 'SubjectLogonId', 'NewProcessId', 'SubjectDomainName', 'TargetLogonId', 'TokenElevationType', 'SubjectUserSid', 'NewProcessName', 'TargetDomainName', 'TargetUserName', 'ParentProcessName', 'TargetUserSid', 'SubjectUserName', 'MandatoryLabel', 'SourceHandleId', 'TargetHandleId', 'SourceProcessId', 'TargetProcessId', 'ObjectServer', 'HandleId', 'ProcessName', 'RestrictedSidCount', 'ObjectName', 'ResourceAttributes', 'PrivilegeList', 'TransactionId', 'AccessMask', 'ObjectType', 'AccessReason', 'AccessList', 'FilterName', 'ChangeType', 'FilterKey', 'CalloutKey', 'Action', 'ProviderName', 'ProviderKey', 'Conditions', 'FilterId', 'UserSid', 'UserName', 'CalloutName', 'FilterType', 'Weight', 'LayerKey', 'LayerId', 'RuleId', 'RuleName', 'ProfileChanged', 'Status', 'GrantedAccess', 'SourceThreadId', 'SourceImage', 'CallTrace', 'UtcTime', 'TargetProcessGUID', 'SourceProcessGUID', 'TargetImage', 'ProcessGuid', 'Image', 'Details', 'EventType', 'TargetObject', 'Description', 'Product', 'Company', 'OriginalFileName', 'User', 'ParentProcessId', 'IntegrityLevel', 'CurrentDirectory', 'Hashes', 'ParentCommandLine', 'TerminalSessionId', 'ParentImage', 'FileVersion', 'ParentProcessGuid', 'LogonGuid', 'LogonId', 'Signature', 'ImageLoaded', 'SignatureStatus', 'Signed', 'TargetFilename', 'CreationUtcTime', 'QueryName', 'QueryStatus', 'QueryResults']

In [12]:
# Display first 25 rows
exe_data.head(25)

,Message,EventID,SourceName,TimeCreated,Hostname,Task,Level,Keywords,Channel,ProviderGuid,@timestamp,SourcePort,LayerName,SourceAddress,Protocol,ProcessId,LayerRTID,FilterRTID,Application,RemoteMachineID,Direction,DestPort,RemoteUserID,DestAddress,ProcessID,CommandLine,SubjectLogonId,NewProcessId,SubjectDomainName,TargetLogonId,TokenElevationType,SubjectUserSid,NewProcessName,TargetDomainName,TargetUserName,ParentProcessName,TargetUserSid,SubjectUserName,MandatoryLabel,SourceHandleId,TargetHandleId,SourceProcessId,TargetProcessId,ObjectServer,HandleId,ProcessName,RestrictedSidCount,ObjectName,ResourceAttributes,PrivilegeList,TransactionId,AccessMask,ObjectType,AccessReason,AccessList,FilterName,ChangeType,FilterKey,CalloutKey,Action,ProviderName,ProviderKey,Conditions,FilterId,UserSid,UserName,CalloutName,FilterType,Weight,LayerKey,LayerId,RuleId,RuleName,ProfileChanged,Status,GrantedAccess,SourceThreadId,SourceImage,CallTrace,UtcTime,TargetProcessGUID,SourceProcessGUID,TargetImage,ProcessGuid,Image,Details,EventType,TargetObject,Description,Product,Company,OriginalFileName,User,ParentProcessId,IntegrityLevel,CurrentDirectory,Hashes,ParentCommandLine,TerminalSessionId,ParentImage,FileVersion,ParentProcessGuid,LogonGuid,LogonId,Signature,ImageLoaded,SignatureStatus,Signed,TargetFilename,CreationUtcTime,QueryName,QueryStatus,QueryResults
1630,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:07.257Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:07.257Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:07.256,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1629,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:07.257Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:07.257Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:07.256,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,The audit log was cleared.\r\nSubject:\r\n\tSe...,1102,Microsoft-Windows-Eventlog,2020-10-29T12:16:07.900Z,WORKSTATION5,104,4,0x4020000000000000,Security,{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148},2020-10-29T12:16:07.900Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1632,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.260Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.260Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.259,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1631,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.260Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.260Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.259,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1633,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,4800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1410,1388.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e1-5f9a-3c36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\system32\conhost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1636,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,4800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1410,1388.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e1-5f9a-3c36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\system32\conhost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1637,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x2000,7728.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e1-5f9a-3c36-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\conhost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1638,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,11136.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1639,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1400,11136.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1640,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:08.494,NaN,NaN,NaN,{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\Explorer.EXE,Binary Data,SetValue,HKU\S-1-5-21-3940915590-64593676-1414006259-50...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1634,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,4800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1388.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e1-5f9a-3c36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\system32\conhost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1635,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.500Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.500Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,4800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1388.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e1-5f9a-3c36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\system32\conhost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1644,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.501Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.501Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x2000,4688.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1643,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.501Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.501Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x2000,4688.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1642,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.501Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.501Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,4688.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1641,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.501Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.501Z,NaN,NaN,NaN,NaN,1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:08.494,NaN,NaN,NaN,{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\Explorer.EXE,Binary Data,SetValue,HKU\S-1-5-21-3940915590-64593676-1414006259-50...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1646,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.502Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.502Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,13264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x2000,4688.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41a0-5f9a-2d36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1645,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.502Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.502Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x2000,4688.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1647,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.503Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.503Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,5852.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1648,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.509Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.509Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1072,9320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,2988.0,C:\windows\Explorer.EXE,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:08.494,{39e4a257-41e0-5f9a-3b36-000000000700},{39e4a257-f1b3-5f8b-a700-000000000700},C:\Windows\System32\WindowsPowerShell\v1.0\pow...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1649,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:08.514Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:08.514Z,NaN,NaN,NaN,NaN,1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:08.509,NaN,NaN,NaN,{39e4a257-f1b3-5f8b-a700-000000000700},C:\windows\Explorer.EXE,Binary Data,SetValue,HKU\S-1-5-21-3940915590-64593676-1414006259-50...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Display last 25 rows
exe_data.tail(25)

,Message,EventID,SourceName,TimeCreated,Hostname,Task,Level,Keywords,Channel,ProviderGuid,@timestamp,SourcePort,LayerName,SourceAddress,Protocol,ProcessId,LayerRTID,FilterRTID,Application,RemoteMachineID,Direction,DestPort,RemoteUserID,DestAddress,ProcessID,CommandLine,SubjectLogonId,NewProcessId,SubjectDomainName,TargetLogonId,TokenElevationType,SubjectUserSid,NewProcessName,TargetDomainName,TargetUserName,ParentProcessName,TargetUserSid,SubjectUserName,MandatoryLabel,SourceHandleId,TargetHandleId,SourceProcessId,TargetProcessId,ObjectServer,HandleId,ProcessName,RestrictedSidCount,ObjectName,ResourceAttributes,PrivilegeList,TransactionId,AccessMask,ObjectType,AccessReason,AccessList,FilterName,ChangeType,FilterKey,CalloutKey,Action,ProviderName,ProviderKey,Conditions,FilterId,UserSid,UserName,CalloutName,FilterType,Weight,LayerKey,LayerId,RuleId,RuleName,ProfileChanged,Status,GrantedAccess,SourceThreadId,SourceImage,CallTrace,UtcTime,TargetProcessGUID,SourceProcessGUID,TargetImage,ProcessGuid,Image,Details,EventType,TargetObject,Description,Product,Company,OriginalFileName,User,ParentProcessId,IntegrityLevel,CurrentDirectory,Hashes,ParentCommandLine,TerminalSessionId,ParentImage,FileVersion,ParentProcessGuid,LogonGuid,LogonId,Signature,ImageLoaded,SignatureStatus,Signed,TargetFilename,CreationUtcTime,QueryName,QueryStatus,QueryResults
2370,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:22.385Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:22.385Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:22.384,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2371,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:22.386Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:22.386Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:22.384,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2372,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:23.385Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:23.385Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:23.384,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2373,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:23.385Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:23.385Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:23.384,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2374,File created:\r\nRuleName: -\r\nUtcTime: 2020-...,11,Microsoft-Windows-Sysmon,2020-10-29T12:16:24.358Z,WORKSTATION5,11,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:24.358Z,NaN,NaN,NaN,NaN,1260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:24.353,NaN,NaN,NaN,{39e4a257-f133-5f8b-1c00-000000000700},C:\windows\System32\svchost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C:\Windows\ServiceState\EventLog\Data\lastaliv...,2020-10-18 07:40:33.283,NaN,NaN,NaN
2375,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:24.385Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:24.385Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:24.384,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2376,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:24.385Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:24.385Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:24.384,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2377,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:25.388Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:25.388Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:25.387,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2378,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:25.388Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:25.388Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:25.387,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2380,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:26.401Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:26.401Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:26.400,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2379,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:26.401Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:26.401Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:26.400,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2381,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.417Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.417Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:27.415,{39e4a257-f247-5f8b-d300-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2382,Process accessed:\r\nRuleName: -\r\nUtcTime: 2...,10,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.417Z,WORKSTATION5,10,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.417Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,944,9372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,0x1000,1060.0,C:\windows\system32\svchost.exe,C:\windows\SYSTEM32\ntdll.dll+9c584|C:\windows...,2020-10-29 04:16:27.415,{39e4a257-4169-5f9a-2136-000000000700},{39e4a257-f132-5f8b-1000-000000000700},C:\windows\system32\backgroundTaskHost.exe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2389,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,QWORD (0x01d6adb2-0xa6c0295f),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2383,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,QWORD (0x01d6adb2-0xa6c0295f),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2384,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,QWORD (0x01d6adaa-0x44fbc15f),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2385,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,QWORD (0x01d6ada1-0xe337595f),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2386,Registry object added or deleted:\r\nRuleName:...,12,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,12,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,NaN,CreateKey,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2387,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,QWORD (0x00000000-0x37ec4871),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2388,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.432Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.432Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,DWORD (0x00000006),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2392,Registry object added or deleted:\r\nRuleName:...,12,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.433Z,WORKSTATION5,12,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.433Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,NaN,CreateKey,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2393,Registry value set:\r\nRuleName: -\r\nEventTyp...,13,Microsoft-Windows-Sysmon,2020-10-29T12:16:27.433Z,WORKSTATION5,13,4,0x8000000000000000,Microsoft-Windows-Sysmon/Operational,{5770385f-c22a-43e0-bf4c-06f5698ffbd9},2020-10-29T12:16:27.433Z,NaN,NaN,NaN,NaN,756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-29 04:16:27.431,NaN,NaN,NaN,{39e4a257-f131-5f8b-0c00-000000000700},C:\windows\system32\lsass.exe,QWORD (0x00000000-0x37ec4871),SetValue,HKLM\System\CurrentControlSet\Services\W32Time...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Checks which feature has ONLY NaN values
exe_data.isna().all()

Message               False
EventID               False
SourceName            False
TimeCreated           False
Hostname              False
Task                  False
Level                 False
Keywords              False
Channel               False
ProviderGuid          False
@timestamp            False
SourcePort            False
LayerName             False
SourceAddress         False
Protocol              False
ProcessId             False
LayerRTID             False
FilterRTID            False
Application           False
RemoteMachineID       False
Direction             False
DestPort              False
RemoteUserID          False
DestAddress           False
ProcessID             False
CommandLine           False
SubjectLogonId        False
NewProcessId          False
SubjectDomainName     False
TargetLogonId         False
TokenElevationType    False
SubjectUserSid        False
NewProcessName        False
TargetDomainName      False
TargetUserName        False
ParentProcessName     False
TargetUserSid         False
SubjectUserName       False
MandatoryLabel        False
SourceHandleId        False
TargetHandleId        False
SourceProcessId       False
TargetProcessId       False
ObjectServer          False
HandleId              False
ProcessName           False
RestrictedSidCount    False
ObjectName            False
ResourceAttributes    False
PrivilegeList         False
TransactionId         False
AccessMask            False
ObjectType            False
AccessReason          False
AccessList            False
FilterName            False
ChangeType            False
FilterKey             False
CalloutKey            False
Action                False
ProviderName          False
ProviderKey           False
Conditions            False
FilterId              False
UserSid               False
UserName              False
CalloutName           False
FilterType            False
Weight                False
LayerKey              False
LayerId               False
RuleId                False
RuleName              False
ProfileChanged        False
Status                False
GrantedAccess         False
SourceThreadId        False
SourceImage           False
CallTrace             False
UtcTime               False
TargetProcessGUID     False
SourceProcessGUID     False
TargetImage           False
ProcessGuid           False
Image                 False
Details               False
EventType             False
TargetObject          False
Description           False
Product               False
Company               False
OriginalFileName      False
User                  False
ParentProcessId       False
IntegrityLevel        False
CurrentDirectory      False
Hashes                False
ParentCommandLine     False
TerminalSessionId     False
ParentImage           False
FileVersion           False
ParentProcessGuid     False
LogonGuid             False
LogonId               False
Signature             False
ImageLoaded           False
SignatureStatus       False
Signed                False
TargetFilename        False
CreationUtcTime       False
QueryName             False
QueryStatus           False
QueryResults          False
dtype: bool

In [ ]:
# Algorithm to count the number of occurrences of each value in each feature and save it to a text file
'''for feature in exe_data.columns.to_list():
    count = exe_data[feature].value_counts()

    # Replace spaces in feature names to avoid invalid filenames
    safe_feature_name = feature.replace(" ", "_")

    #with open(f"{safe_feature_name}.txt", "w") as f:
        f.write(count.to_string())'''

### Execution Log Data Visualization

### Execution Log Modeling

## Credential Access Logs

In [16]:
# Reading the logs from the credential access URL
zipFileRequest = requests.get(cred_url)
zipFile = ZipFile(BytesIO(zipFileRequest.content))
datasetJSONPath = zipFile.extract(zipFile.namelist()[0])

# Storing logs into a dataframe
cred_df = pd.read_json(path_or_buf=datasetJSONPath, lines=True)

### Credential Access Log Exploratory Data Analysis

In [17]:
# Sorting the logs by timestamp in ascending order
cred_data = cred_df.sort_values(by='@timestamp', ascending=True)

# Get all columns in the dataset
cred_columns = cred_data.columns.tolist()
print(cred_columns)

['tags', 'TargetProcessGUID', '@version', 'EventType', 'Version', 'ThreadID', 'EventTime', 'Task', 'AccountType', 'SourceProcessGUID', 'CallTrace', 'Channel', 'SourceName', 'OpcodeValue', 'Hostname', '@timestamp', 'Message', 'SourceModuleName', 'ProcessId', 'SourceImage', 'EventReceivedTime', 'port', 'AccountName', 'UtcTime', 'GrantedAccess', 'Domain', 'ExecutionProcessID', 'host', 'SourceProcessId', 'SourceThreadId', 'Severity', 'TargetProcessId', 'SeverityValue', 'EventID', 'UserID', 'ProviderGuid', 'RecordNumber', 'SourceModuleType', 'Keywords', 'TargetImage', 'RuleName', 'EventTypeOrignal', 'TargetObject', 'Image', 'ProcessGuid', 'SourcePort', 'Category', 'Opcode', 'Application', 'LayerRTID', 'LayerName', 'SourceAddress', 'FilterRTID', 'Protocol', 'DestAddress', 'Direction', 'RemoteMachineID', 'DestPort', 'RemoteUserID', 'DestinationPortName', 'DestinationIp', 'SourceIp', 'Initiated', 'DestinationHostname', 'SourceHostname', 'DestinationPort', 'SourceIsIpv6', 'User', 'DestinationIsIpv6', 'SourcePortName', 'ContextInfo', 'Payload', 'ActivityID', 'SubjectLogonId', 'PrivilegeList', 'SubjectDomainName', 'SubjectUserSid', 'SubjectUserName', 'TargetDomainName', 'ElevatedToken', 'TargetOutboundDomainName', 'IpPort', 'ImpersonationLevel', 'ProcessName', 'KeyLength', 'TargetOutboundUserName', 'RestrictedAdminMode', 'LogonProcessName', 'LogonGuid', 'WorkstationName', 'TargetLinkedLogonId', 'TargetLogonId', 'TargetUserSid', 'TransmittedServices', 'IpAddress', 'LmPackageName', 'TargetUserName', 'AuthenticationPackageName', 'VirtualAccount', 'LogonType', 'GroupMembership', 'EventIdx', 'EventCountTotal', 'TargetFilename', 'CreationUtcTime', 'OriginalFileName', 'Signed', 'SignatureStatus', 'FileVersion', 'Company', 'Signature', 'ImageLoaded', 'Hashes', 'Description', 'Product', 'Status', 'EnabledPrivilegeList', 'DisabledPrivilegeList', 'Device', 'Details', 'PipeName', 'SourceHandleId', 'TargetHandleId', 'ObjectServer', 'HandleId', 'ObjectName', 'ObjectType', 'AccessMask', 'AccessList', 'ResourceAttributes', 'TransactionId', 'AccessReason', 'RestrictedSidCount', 'ParentCommandLine', 'ParentProcessId', 'CurrentDirectory', 'IntegrityLevel', 'CommandLine', 'ParentImage', 'LogonId', 'TerminalSessionId', 'ParentProcessGuid', 'NewProcessName', 'NewProcessId', 'TokenElevationType', 'MandatoryLabel', 'ParentProcessName', 'ShareLocalPath', 'ShareName', 'RelativeTargetName', 'NewSd', 'OldSd', 'QueryResults', 'QueryName', 'QueryStatus', 'Service']

### Credential Access Log Data Visualization

### Credential Access Log Modeling